import java.util.Scanner;

// Unit 2, Topic 2.1, Classes and Objects, 11/03/2021, v.0.1

public class Student {
    // these are instance variable
    private int studentID;
    private int gradeLevel;
    private double gradePointAge;
    private String studentName;

    // creating a constructor
    public Student() {
        this.studentID = 0;
        this.gradeLevel = 0;
        this.gradePointAge = 0.0;
        this.studentName = "";
        
    }

}